logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      database: ${DATABASE_NAME:db}
      uri: ${DATABASE_URI:mongodb://admin:admin@localhost:27017/?authSource=db}

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    lettuce:
      pool:
        max-idle: 10
        min-idle: 2
        max-active: 10
        max-wait: 2

toast:
  alimtalk:
    url: https://f63a7387-2ff7-47f4-b081-33cfa945fed7.mock.pstmn.io
    appKey: xxx
    secretKey: xxx

kafka:
  brokers:
    bootstrap: ${KAFKA_BROKERS:127.0.0.1:19092}
